# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title: 山水淡
title: A place for myself to write something
email: uames.ji@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is a place I can write something for myself, maybe for someone
  like you. I like reading, but I want to write something also. Thanks
  for reading!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://uames.github.io" # the base hostname & protocol for your site
twitter_username: uamesa
github_username:  uames

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

encoding: "utf-8"
production_url : http://uames.github.io
BASE_PATH : /blog
